[uWSGI] getting INI configuration from /srv/www/flask_window/uwsgi.ini
open("./python35_plugin.so"): No such file or directory [core/utils.c line 3686]
!!! UNABLE to load uWSGI plugin: ./python35_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.15 (64bit) on [Tue Mar  6 09:41:51 2018] ***
compiled with version: 5.4.0 20160609 on 10 October 2017 15:42:54
os: Linux-4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /srv/www/flask_window
detected binary path: /home/server/.local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 62624
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5234 fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x1a555d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "./app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "./app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "./app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 16483, cores: 1)
SystemError: ../Objects/listobject.c:245: bad argument to internal function
Traceback (most recent call last):
  File "/srv/www/flask_window/manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "/srv/www/flask_window/app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "/srv/www/flask_window/app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "/srv/www/flask_window/app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 16483|app: -1|req: -1/1] 172.16.0.88 () {46 vars in 806 bytes} [Tue Mar  6 09:42:09 2018] GET /api/ => generated 21 bytes in 13 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:245: bad argument to internal function
Traceback (most recent call last):
  File "/srv/www/flask_window/manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "/srv/www/flask_window/app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "/srv/www/flask_window/app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "/srv/www/flask_window/app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 16483|app: -1|req: -1/2] 172.16.0.88 () {46 vars in 785 bytes} [Tue Mar  6 09:42:09 2018] GET /favicon.ico => generated 21 bytes in 11 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:245: bad argument to internal function
Traceback (most recent call last):
  File "/srv/www/flask_window/manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "/srv/www/flask_window/app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "/srv/www/flask_window/app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "/srv/www/flask_window/app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 16483|app: -1|req: -1/3] 172.16.0.88 () {48 vars in 837 bytes} [Tue Mar  6 09:42:15 2018] GET /api/ => generated 21 bytes in 8 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:245: bad argument to internal function
Traceback (most recent call last):
  File "/srv/www/flask_window/manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "/srv/www/flask_window/app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "/srv/www/flask_window/app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "/srv/www/flask_window/app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 16483|app: -1|req: -1/4] 172.16.0.88 () {50 vars in 838 bytes} [Tue Mar  6 09:42:15 2018] GET /favicon.ico => generated 21 bytes in 11 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
[uWSGI] getting INI configuration from /srv/www/flask_window/uwsgi.ini
open("./python35_plugin.so"): No such file or directory [core/utils.c line 3686]
!!! UNABLE to load uWSGI plugin: ./python35_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.15 (64bit) on [Tue Mar  6 09:42:24 2018] ***
compiled with version: 5.4.0 20160609 on 10 October 2017 15:42:54
os: Linux-4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /srv/www/flask_window
detected binary path: /home/server/.local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 62624
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5234 fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x20ca5d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "./app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "./app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "./app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 16490, cores: 1)
SystemError: ../Objects/listobject.c:245: bad argument to internal function
Traceback (most recent call last):
  File "/srv/www/flask_window/manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "/srv/www/flask_window/app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "/srv/www/flask_window/app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "/srv/www/flask_window/app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 16490|app: -1|req: -1/1] 172.16.0.88 () {48 vars in 837 bytes} [Tue Mar  6 09:42:37 2018] GET /api/ => generated 21 bytes in 12 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:245: bad argument to internal function
Traceback (most recent call last):
  File "/srv/www/flask_window/manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "/srv/www/flask_window/app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "/srv/www/flask_window/app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "/srv/www/flask_window/app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 16490|app: -1|req: -1/2] 172.16.0.88 () {50 vars in 838 bytes} [Tue Mar  6 09:42:37 2018] GET /favicon.ico => generated 21 bytes in 8 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:245: bad argument to internal function
Traceback (most recent call last):
  File "/srv/www/flask_window/manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "/srv/www/flask_window/app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "/srv/www/flask_window/app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "/srv/www/flask_window/app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 16490|app: -1|req: -1/3] 172.16.0.88 () {48 vars in 837 bytes} [Tue Mar  6 09:42:41 2018] GET /api/ => generated 21 bytes in 12 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
SystemError: ../Objects/listobject.c:245: bad argument to internal function
Traceback (most recent call last):
  File "/srv/www/flask_window/manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "/srv/www/flask_window/app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "/srv/www/flask_window/app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "/srv/www/flask_window/app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
--- no python application found, check your startup logs for errors ---
[pid: 16490|app: -1|req: -1/4] 172.16.0.88 () {50 vars in 838 bytes} [Tue Mar  6 09:42:41 2018] GET /favicon.ico => generated 21 bytes in 12 msecs (HTTP/1.1 500) 2 headers in 83 bytes (0 switches on core 0)
[uWSGI] getting INI configuration from /srv/www/flask_window/uwsgi.ini
open("./python35_plugin.so"): No such file or directory [core/utils.c line 3686]
!!! UNABLE to load uWSGI plugin: ./python35_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.15 (64bit) on [Tue Mar  6 09:49:34 2018] ***
compiled with version: 5.4.0 20160609 on 10 October 2017 15:42:54
os: Linux-4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /srv/www/flask_window
detected binary path: /home/server/.local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 62624
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5234 fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x255ffd0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
WSGI app 0 (mountpoint='') ready in 0 seconds on interpreter 0x255ffd0 pid: 16832 (default app)
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 16832, cores: 1)
/usr/local/lib/python3.5/dist-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
[pid: 16832|app: 0|req: 1/1] 172.16.0.88 () {48 vars in 837 bytes} [Tue Mar  6 09:49:58 2018] GET /api/ => generated 69 bytes in 13 msecs (HTTP/1.1 200) 5 headers in 254 bytes (2 switches on core 0)
[pid: 16832|app: 0|req: 2/2] 172.16.0.88 () {50 vars in 838 bytes} [Tue Mar  6 09:49:59 2018] GET /favicon.ico => generated 81 bytes in 2 msecs (HTTP/1.1 200) 5 headers in 254 bytes (2 switches on core 0)
[uWSGI] getting INI configuration from /srv/www/flask_window/uwsgi.ini
open("./python35_plugin.so"): No such file or directory [core/utils.c line 3686]
!!! UNABLE to load uWSGI plugin: ./python35_plugin.so: cannot open shared object file: No such file or directory !!!
*** Starting uWSGI 2.0.15 (64bit) on [Tue Mar  6 09:51:01 2018] ***
compiled with version: 5.4.0 20160609 on 10 October 2017 15:42:54
os: Linux-4.4.0-116-generic #140-Ubuntu SMP Mon Feb 12 21:23:04 UTC 2018
nodename: ubuntu
machine: x86_64
clock source: unix
pcre jit disabled
detected number of CPU cores: 8
current working directory: /srv/www/flask_window
detected binary path: /home/server/.local/bin/uwsgi
uWSGI running as root, you can use --uid/--gid/--chroot options
*** WARNING: you are running uWSGI as root !!! (use the --uid flag) *** 
*** WARNING: you are running uWSGI without its master process manager ***
your processes number limit is 62624
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uwsgi socket 0 bound to TCP address 127.0.0.1:5234 fd 3
Python version: 3.5.2 (default, Nov 23 2017, 16:37:01)  [GCC 5.4.0 20160609]
*** Python threads support is disabled. You can enable it with --enable-threads ***
Python main interpreter initialized at 0x14d75d0
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 72768 bytes (71 KB) for 1 cores
*** Operational MODE: single process ***
Traceback (most recent call last):
  File "manage.py", line 8, in <module>
    from app.flask_init import create_app, db
  File "./app/flask_init.py", line 7, in <module>
    from .ext import  db, app, redis
  File "./app/ext.py", line 6, in <module>
    from .json_response import MyFlask
  File "./app/json_response.py", line 6, in <module>
    from flask import Response, jsonify, Flask
ImportError: No module named 'flask'
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI worker 1 (and the only) (pid: 16928, cores: 1)
